CFLAGS=-Wall -g -DNDEBUG

clean:
	rm -f hello_world
	rm -f ex7
	rm -f ex8
	rm -f ex9
	rm -f ex10
	rm -f ex11
	rm -f ex12
	rm -f ex13
	rm -f ex14
	rm -f ex15
	rm -f ex16
	rm -f ex17
	rm -f ex18
	rm -f ex19
	rm -f ex20
	rm -f ex22.o
	rm -f ex22_main
	rm -f ex23
	rm -f ex24
	rm -f ex25
